# Generated by Django 2.1.7 on 2019-04-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_addsubcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('menuid', models.AutoField(primary_key=True, serialize=False)),
                ('menunm', models.CharField(max_length=50)),
                ('menuprice', models.IntegerField()),
                ('menudiscription', models.CharField(max_length=50)),
                ('menuimg', models.CharField(max_length=100)),
                ('menucat', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='package',
            fields=[
                ('packid', models.AutoField(primary_key=True, serialize=False)),
                ('packnm', models.CharField(max_length=50)),
                ('packprice', models.IntegerField()),
                ('packdiscription', models.CharField(max_length=50)),
                ('packimg', models.CharField(max_length=100)),
                ('packduration', models.CharField(max_length=50)),
            ],
        ),
    ]
