# Generated by Django 4.1 on 2022-10-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('txnid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=100)),
                ('adsid', models.CharField(max_length=100)),
                ('adsprice', models.CharField(max_length=100)),
                ('ptime', models.CharField(max_length=100)),
            ],
        ),
    ]
