# Generated by Django 2.1.7 on 2019-04-04 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregister',
            old_name='user_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='userregister',
            old_name='user_contact',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='userregister',
            old_name='user_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='userregister',
            old_name='user_dob',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='userregister',
            old_name='user_fullname',
            new_name='mobile_number',
        ),
        migrations.RenameField(
            model_name='userregister',
            old_name='city_id',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='userregister',
            old_name='user_password',
            new_name='select_city',
        ),
    ]
