# Generated by Django 2.1.7 on 2019-04-04 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0002_auto_20190404_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregister',
            old_name='password',
            new_name='city_id',
        ),
        migrations.RenameField(
            model_name='userregister',
            old_name='address',
            new_name='user_address',
        ),
        migrations.RenameField(
            model_name='userregister',
            old_name='dob',
            new_name='user_contact',
        ),
        migrations.RenameField(
            model_name='userregister',
            old_name='full_name',
            new_name='user_dob',
        ),
        migrations.RenameField(
            model_name='userregister',
            old_name='email',
            new_name='user_email',
        ),
        migrations.RenameField(
            model_name='userregister',
            old_name='mobile_number',
            new_name='user_fullname',
        ),
        migrations.RenameField(
            model_name='userregister',
            old_name='select_city',
            new_name='user_password',
        ),
    ]
